# Generated by Django 5.1.7 on 2025-03-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='agent_status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'ACTIVE'), ('BLOCKED', 'BLOCKED'), ('DELETED', 'DELETED')], default='AVAILABLE', max_length=50, verbose_name='Agent Status'),
        ),
    ]
